name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
      
    env:
      rc: ""
  
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
        
      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      
      - name: Print Latest Tag
        run: echo ${{ steps.get-latest-tag.outputs.tag }}
    
      - name: create env
        run: $rc="hello"

      - name: get env
        run: echo "${{ env.rc }}"
#      - name: Change Latest Tag
#        uses: christian-draeger/increment-semantic-version@1.0.2
#        with:
#          current-version: 
