name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      
      - name: ls
        run: ls
      
      - name: Get latest Github release per branch
        run: git tag
        id: gittag
      
      - name: get output tag
        run: echo ${{ steps.gittag.output }}
