name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: ls
        run: ls
        
      - uses: ctrlaltdev/latest-release-json-action@1
        with:
          releases: '[...]'
