name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: ls
        run: ls
        
      - uses: rlespinasse/github-slug-action@v4.3.0
      - name: Get previous release tag
        id: previous-release
        uses: sammcoe/get-previous-release-action@v1
