name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  get-change-prerelease-tag:
    runs-on:
      - ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: payload
        run: echo ${{ toJson(github) }}
        
      - name: Get Latest Prerelease Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      
      - name: Increment Release Candidate Version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.get-latest-tag.outputs.tag }}
          version-fragment: rc

#   print-output-of-previous-job:
#     runs-on:
#       - ubuntu-latest
      
