name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: checkout
        run: actions/checkout@v3
        
      - name: Get Latest Release Tag
        uses: ctrlaltdev/latest-release-json-action@v1.0.1
