name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: checkout
        run: git clone https://github.com/Hakob771/run-integration-tests.git
        
      - name: git tag
        run: cd run-integration-tests && git tag
