name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
        
      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      
      - name: Print Latest Tag
        run: echo ${{ steps.get-latest-tag.outputs.tag }}
        
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          exclude: '*-rc*'
          
          
      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
