name: run integration tests

on:
  push:
    branches:
      - dev

env:
  RC: ""

jobs:
  setReleaseCandidate:
    runs-on:
      - ubuntu-latest
    
    steps:
      - name: set env
        env:
          RC: "esim"
  getRC:
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: get env
        run: echo "${{ env.RC }}"
