name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  install-aws-cli:
    runs-on: 
      - ubuntu-latest
    
    steps:
      - name: install aws-cli
        run: docker --version
