name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  setReleaseCandidate:
    runs-on:
      - ubuntu-latest
    
    steps:
      - name: set env
        run: ${{ github.workflow }}
