name: run integration tests

on:
  push:
    branches:
      - dev

jobs:
  run-integration-tests:
    runs-on:
      - ubuntu-latest
        
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Get the latest release upload url, tag, date
        uses: jossef/action-latest-release-info@v1.2.0

